language: ruby
rvm:
  - 2.0.0
before_script:
  - bundle exec thor setup:dev_env
  - npm install bower
  - bundle exec rake bower:install
branches:
  only:
    - master
    - develop
notifications:
  webhooks: https://mortik.slack.com/services/hooks/travis?token=aqp1ZDxk4YATzbB2XC8b36kn
