language: ruby
rvm:
  - 2.1.4
before_script:
  - bundle exec thor setup:dev_env
  - bundle exec rake db:create db:migrate
  - npm install bower
  - bundle exec rake bower:install
branches:
  only:
    - master
    - develop
notifications:
  webhooks: https://mortik.slack.com/services/hooks/travis?token=aqp1ZDxk4YATzbB2XC8b36kn
